### ISSUE TITLE
# in url

### ISSUE THREAD

**Issue by usharanimudugal** [apifytech/actor-google-search-scraper#14]
https://api.apify.com/v2/datasets/GHkzt2HRL2Nk37pDM/items?format=json&clean=1

Most of the records in organic results here have a # for url

**Comment by jancurn** [comment]
We tried to re-run your query and it works fine. Perhaps Google was A/B testing new layout. Anyway, we'll try to identify it and fix it. Thanks for the report!

**Comment by jancurn** [comment]
Fixed in https://github.com/apifytech/actor-google-search-scraper/pull/15

**Comment by jancurn** [comment]
New actor has been deployed
