### ISSUE TITLE
Mobile results are not working

### ISSUE THREAD

**Issue by jancurn** [apifytech/actor-google-search-scraper#19]
Seems Google changed a layout of the pages...

**Comment by jancurn** [comment]
Previously, mobile results were only missing "description" and have wrong "displayedUrl", but it seems now they are broken completely.

**Comment by mnmkng** [comment]
@jancurn I looked at it and it's caused by the fact that we receive JS disabled HTML instead of full JS enabled HTML through SERP now. It obviously has a different structure and the extraction fails.

**Comment by pocesar** [comment]
was going to post about this, since I'm hands-on right now, should I try to fix and submit a PR?

**Comment by jancurn** [comment]
@pocesar That would be awesome!

**Comment by pocesar** [comment]
I'm on it
