### ISSUE TITLE
resultsTotal is 0

### ISSUE THREAD

**Issue by metalwarrior665** [apifytech/actor-google-search-scraper#36]
https://api.apify.com/v2/datasets/5v470MmwT1ktbJrV5/items?format=json&clean=1
https://api.apify.com/v2/key-value-stores/LdoV5x73zGxTGW2pI/records/Cb6oNzPfLSNURUp.html?disableRedirect=true

**Comment by metalwarrior665** [comment]
@AndreyBykov This was fixed, right?

**Comment by jancurn** [comment]
Yes, fixed and deployed.
