### ISSUE TITLE
Uk country code and tld not matching

### ISSUE THREAD

**Issue by gchokeen** [apifytech/actor-google-search-scraper#37]
I selected country from drop down as `united kingdom` (UK) but search url was not referring to `.co.uk`. because google_domain.json has this `"GB": "google.co.uk"`. So it's not matching

**Comment by jancurn** [comment]
Good catch, fixed in https://github.com/apifytech/actor-google-search-scraper/commit/c7dd206ae4af9a3744cb1be375fc437916ac31c1, will be deployed later today

**Comment by jancurn** [comment]
Deployed.
