### ISSUE TITLE
Remove deprecation warning

### ISSUE THREAD

**Issue by jancurn** [apifytech/actor-google-search-scraper#5]
The actor log shows:

```
2019-03-19T21:13:33.283Z WARNING: CheerioCrawler: options.requestFunction is deprecated. Use BasicCrawler instead.
```

It doesn't look good for new users.

**Comment by mtrunkat** [comment]
I was waiting for beforeRequestFunction that is in upcoming BETA of SDK.

**Comment by jancurn** [comment]
Seems to be fixed now in https://github.com/apifytech/actor-google-search-scraper/pull/8
