### ISSUE TITLE
description for Country not clear

### ISSUE THREAD

**Issue by glgoose** [apifytech/actor-google-search-scraper#7]
- Mention that if you select a country it goes to the google domain for that country. example: Belgium -> google.be
- Mention that if you select Country it also sets the SERP proxy to the location for that country
- Use "Country" instead of "Country code", same for "Language code" because in dropdown the full names are mentioned and not the codes
![image](https://user-images.githubusercontent.com/48956933/55899191-808db900-5bc4-11e9-818f-deae276c6c27.png)

**Comment by jancurn** [comment]
One more thing - we shouldn't pass `gl` parameter at all, setting the hostname is enough. Some proxy providers can't handle the parameter and then we fallback to worse providers. We should update the comments and readme to describe this.

Same holds for the `hl` parameter - users shouldn't set it unless really needed.

So, we should change the "None" to "Default" in the dropdowns to make it more obvious how it works.

**Comment by jancurn** [comment]
Fixed in https://github.com/apifytech/actor-google-search-scraper/pull/8
